# Setup
title:               diconium SESS1ON Prompt Engineering Workshop 
tagline:             ''
description:         'Modules in the Workshop'
baseurl:             'diconiumneil.github.io'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Neil Sinclair
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

