# Setup
title:               diconium SESS1ON Prompt Engineering Workshop 
tagline:             ''
description:         'Modules in the Workshop'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Neil Sinclair
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

baseurl: "https://github.com/dda-core-team/diconiumneil.github.io"